# full list of linters available: https://golangci-lint.run/usage/linters/
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    # - contextcheck
    - errname
    - gocheckcompilerdirectives
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - maintidx
    - misspell
    - nilnil
    - noctx
    - nolintlint
    - predeclared
    - reassign
    - sloglint
    - spancheck
    - stylecheck
    # - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars

linters-settings:
  gosec:
    excludes:
      - G404 # Insecure random number source (rand)
