version: '2.2'

services:
    openhab30:
        image: "openhab/openhab:3.0.4"
        ports:
            - "8083:8083"
            - "8343:8443"
        volumes:
            - "./openhab30_addons:/openhab/addons"
            - "./openhab30_conf:/openhab/conf"
            - "./openhab30_userdata:/openhab/userdata"
        environment:
            OPENHAB_HTTP_PORT: "8083"
            OPENHAB_HTTPS_PORT: "8443"
            EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/London"
