package event

// ErrorEvent is used for errors generated by the client
type ErrorEvent struct {
	eventType Type
	err       error
}

// NewErrorEvent creates ClientError event type
func NewErrorEvent(err error) ErrorEvent {
	return ErrorEvent{
		eventType: TypeClientError,
		err:       err,
	}
}

// Topic is always empty on ErrorEvent
func (e ErrorEvent) Topic() string {
	return ""
}

// Type is ClientError
func (e ErrorEvent) Type() Type {
	return e.eventType
}

// Error returns the error that triggered the event
func (e ErrorEvent) Error() error {
	return e.err
}

var _ Event = &ErrorEvent{}
