package event

// SystemEvent is used for system events not generated by openHAB
type SystemEvent struct {
	eventType Type
}

// NewSystemEvent creates an ClientConnected or ClientDisconnected event types
func NewSystemEvent(eventType Type) SystemEvent {
	return SystemEvent{
		eventType: eventType,
	}
}

// Topic is always empty on SystemEvent
func (e SystemEvent) Topic() string {
	return ""
}

// Type is either ClientConnected or ClientDisconnected
func (e SystemEvent) Type() Type {
	return e.eventType
}

var _ Event = &SystemEvent{}
