package openhab

type RuleData struct {
	// ID will be autogenerated if empty
	ID          string
	Name        string
	Description string
	// Context can contain anything you need to access inside the rule (database connection, etc)
	Context interface{}
}
